# -*- coding: utf-8 -*-
"""LAB5_2024-1-60-228.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LCIqRxLxIp8Bv7uxcTOJyihrySm-FJa
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

# Load the CSV file
df = pd.read_csv("/content/adult_income.csv") # Replace with your CSV path
df

"""### 1. Basic Exploration

Display the first 5 rows
"""

print("First 5 rows:")
display(df.head())

"""Display the last 5 rows"""

print("Last 5 rows:")
display(df.tail())

"""Show the shape of the dataset"""

print("Dataset shape (rows, columns):", df.shape)

"""Check the data types of all columns"""

print("Data types of each column:")
print(df.dtypes)

"""Show summary statistics"""

print("Summary statistics for numerical features:")
display(df.describe())

"""### 2. Handle Missing Values

Check for missing/null values
"""

print("Missing values in each column:")
print(df.isnull().sum())

"""**Now you have to complete the tasks on your own dataset**

Do a complete EDA (Exploratory Data Analysis)
1. Basic Exploration
Display the first 5 rows
Display the last 5 rows
Show the shape of the dataset
Check the data types of all columns
Show summary statistics
2. Data Cleaning:
Check for missing/null values
Handle missing values appropriately
Check for duplicate rows and remove them if necessary.
Briefly explain the method you used
3. Data Visualization
Create the following plots (with proper titles and labels):
Histogram
Boxplot
Scatter plot
Line plot
Bar plot
Pie chart
Count plot
Correlation matrix (heatmap)
Explore additional plots or visualizations as you see fit
4. Discussion
For each plot, provide a brief explanation of the findings obtained from it.

5. Bivariate Analysis
Analyze relationships between features in your dataset.

For example, using the attached sample dataset as a reference, the analysis can explore relationships such as: Age vs Income, Education vs Income, Gender vs Income, Hours-per-week vs Income, Occupation vs Income, etc.

You may refer to the example dataset and notebook attached and follow them to apply the analysis to your own dataset.

Dataset Details: https://www.cs.toronto.edu/~delve/data/adult/adultDetail.html

#Handle Missing values

#2.C
"""

num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows found: {num_duplicates}")

if num_duplicates > 0:
  #Removing Duplicate values
    df.drop_duplicates(inplace=True)

    print(f"Removed {num_duplicates} duplicate rows using df.drop_duplicates(inplace=True).")
else:
    print("No duplicate rows found.")

print("New DataFrame shape (rows, columns):", df.shape)

import matplotlib.pyplot as plt
import seaborn as sns

# Identify numerical columns
numerical_cols = df.select_dtypes(include=np.number).columns

print("Histograms for Numerical Features.")
for col in numerical_cols:
    plt.figure(figsize=(10, 6))
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency -Y Axis')
    plt.show()
print("Histogram Charts are Given.")

print("Boxplots for Numerical Features...")
for col in numerical_cols:
    plt.figure(figsize=(10, 6))
    sns.boxplot(y=df[col])
    plt.title(f'Boxplot of {col}')
    plt.ylabel(col)
    plt.show()
print("Boxplots are given.")

print("Generating Count Plots for Categorical Features...")
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    plt.figure(figsize=(12, 6))
    sns.countplot(y=df[col], order = df[col].value_counts().index)
    plt.title(f'Count Plot of {col}')
    plt.xlabel('Count')
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()
print("Count plots generated successfully.")

print("Correlation Matrix Heatmap for Numerical Features.")

# Calculate the correlation matrix
correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix of Numerical Features.')
plt.show()

print("Correlation matrix heatmap.")

"""## Additional Plots are given
Capital Loss vs hours per week Scatter Plot
"""

print(" Scatter Plot: Capital Loss vs Hours-per-Week.")

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['capital-loss'], y=df['hours-per-week'])
plt.title('Scatter Plot of Capital Loss vs Hours-per-Week')
plt.xlabel('Capital Loss')
plt.ylabel('Hours-per-Week')
plt.show()

print("Scatter plot of Capital Loss vs Hours-per-Week.")

"""# Additional Plot
Capital Gain vs Hours per week scatter Plot
"""

print("Scatter Plot: Capital Gain vs Hours-per-Week.")

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['capital-gain'], y=df['hours-per-week'])
plt.title('Scatter Plot of Capital Gain vs Hours-per-Week')
plt.xlabel('Capital Gain x AXIS')
plt.ylabel('Hours-per-Week-Y AXIS')
plt.show()

print("Scatter plot of Capital Gain vs Hours-per-Week.")

print("Line Plot- Average hours-per-week vs Age.")

# Calculate the average hours-per-week for each age
average_hours_per_week_by_age = df.groupby('age')['hours-per-week'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x='age', y='hours-per-week', data=average_hours_per_week_by_age)
plt.title('Average Hours-per-Week by Age')
plt.xlabel('Age')
plt.ylabel('Average Hours-per-Week')
plt.grid(True)
plt.show()

print("Line plot")

"""This Graph shows Avarqage Hours Working per week. Here is X axis is age and Y axis is working Hours.We can see On age interval [30-60] Avg Hours is higger then other age people working."""

print("Bar Plot: Average hours-per-week by Workclass.")

# weekworkclass: average hours
average_hours_per_week_by_workclass = df.groupby('workclass')['hours-per-week'].mean().reset_index()

plt.figure(figsize=(12, 7))
sns.barplot(x='workclass', y='hours-per-week', data=average_hours_per_week_by_workclass, palette='viridis')
plt.title('Average Hours-per-Week by Workclass')
plt.xlabel('Workclass')
plt.ylabel('Average Hours-per-Week')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print("Bar plot.")

print("Pie Charts for Selected Categorical Feature is here")

categorical_cols = df.select_dtypes(include='object').columns

selected_for_pie_charts = []
for col in categorical_cols:
    if df[col].nunique() <= 10:
        selected_for_pie_charts.append(col)

if not selected_for_pie_charts:
    print("No suitable categorical columns found for pie chart generation (example: with <= 10 unique values).")
else:
    for col in selected_for_pie_charts:
        counts = df[col].value_counts()
        labels = counts.index
        sizes = counts.values

        plt.figure(figsize=(10, 8))
        plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140)
        plt.title(f'Distribution of {col}')
        plt.axis('equal')
        plt.show()

print("Pie charts Creation.")

print("Boxplot: Age vs Income...")

plt.figure(figsize=(10, 6))
sns.boxplot(x='income', y='age', data=df)
plt.title('Age Distribution by Income Level')
plt.xlabel('Income')
plt.ylabel('Age')
plt.show()

print("Boxplot of Age vs Income.")

print("Boxplot: Hours-per-week vs Income...")

plt.figure(figsize=(10, 6))
sns.boxplot(x='income', y='hours-per-week', data=df)
plt.title('Hours-per-week Distribution by Income Level')
plt.xlabel('Income')
plt.ylabel('Hours-per-week')
plt.show()

print("Boxplot of Hours-per-week vs Income")

print("Generating Boxplot: Educational-num vs Income...")

plt.figure(figsize=(10, 6))
sns.boxplot(x='income', y='educational-num', data=df)
plt.title('Educational-num Distribution by Income Level')
plt.xlabel('Income')
plt.ylabel('Educational-num')
plt.show()

print("Boxplot of Educational-num vs Income generated successfully.")

print("Count PLOT by Gender")

plt.figure(figsize=(16, 10))
sns.countplot(x='income', hue='gender', data=df, palette='viridis')
plt.title('Income Distribution by Gender')
plt.xlabel('Income')
plt.ylabel('Count')
plt.show()

print("Count plot of Income Distribution by Gender")

print("Count plot BY Occapation")
plt.figure(figsize=(15, 10))
sns.countplot(x='occupation', hue='income', data=df, palette='viridis')
plt.title('Income Distribution by Occupation')
plt.xlabel('Occupation')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print("Count plot of Income Distribution BY Occupation.")

"""This is the graph of Count plot of Income Distribution BY Occupation. If we look into this graph we can se different types of occapation and their number of working people on that occation.if we look into salary the higgest profession is  Exec- Managerial with almost 3000 works.The higgest profession working people is ADM-Clercal"""