# -*- coding: utf-8 -*-
"""pandas_lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vaB37fdZXCWIYDCzS8RbwW79l_1sRTjo

1. Load the CSV file into a DataFrame.
2. Display the first 10 rows of the DataFrame.
3. Display the last 5 rows of the DataFrame.
4. Print information about the data
5. In the "temp" column, replace NULL values with the mean of that column.
6. In the "rain" column, replace NULL values with the median of that column.
7. In the "month" and "year" columns, replace NULL values with the mode of each column, but only if NULL values are present.

Load the Rain_dataset.csv file into a pandas DataFrame.

**1.** import pandas as pd
# df = pd.read_csv('/content/Rain_dataset.csv')
"""

import pandas as pd
df = pd.read_csv('/content/Rain_dataset.csv')

"""# 2. Display the first 10 rows of the DataFrame."""

print("Dataset loaded successfully.\nFirst 5 rows are:")
print(df.head())

"""# 3. Display the last 5 rows of the DataFrame."""

print("\nLast 5 rows of the DataFrame:")
print(df.tail(5))

print("\nDataFrame Information:")
df.info()

"""# Print information about the data
Here I have add mean values in the missing null values and finally checked that if any null values are reamined or not...
"""

mean_temp = df['tem'].mean()
df['tem'].fillna(mean_temp, inplace=True)
print(f"Mean of 'tem' column calculated as: {mean_temp:.2f}")
print(f"NULL values in 'tem' column after filling: {df['tem'].isnull().sum()}")

mean_temp = df['tem'].mean()
df['tem'] = df['tem'].fillna(mean_temp)
print(f"Mean of 'tem' column calculated as: {mean_temp:.2f}")
print(f"NULL values in 'tem' column after filling: {df['tem'].isnull().sum()}")

"""**5**
Following the defined subtask, I need to calculate the median of the 'rain' column and then fill any missing values in that column with this calculated median. Finally, I will print the count of null values in the 'rain' column to verify the operation.


"""

median_rain = df['rain'].median()
df['rain'] = df['rain'].fillna(median_rain)
print(f"Median of 'rain' column calculated as: {median_rain:.2f}")
print(f"NULL values in 'rain' column after filling: {df['rain'].isnull().sum()}")

for col in ['Month', 'Year']:
    if df[col].isnull().any():
        mode_val = df[col].mode()[0]
        df[col] = df[col].fillna(mode_val)
        print(f"Mode of '{col}' column calculated as: {mode_val:.0f}")
    print(f"NULL values in '{col}' column after filling: {df[col].isnull().sum()}")

print("\nFinal NULL value counts after handling missing data:")
print(f"NULL values in 'tem' column: {df['tem'].isnull().sum()}")
print(f"NULL values in 'rain' column: {df['rain'].isnull().sum()}")
print(f"NULL values in 'Month' column: {df['Month'].isnull().sum()}")
print(f"NULL values in 'Year' column: {df['Year'].isnull().sum()}")

"""## Summary:

### Data Analysis Key Findings
*   The `Rain_dataset.csv` file was successfully loaded into a DataFrame containing 1380 entries and 4 columns: 'tem', 'Month', 'Year', and 'rain'.
*   All columns were initially of `float64` data type.
*   Initial inspection revealed missing values in all specified columns:
    *   'tem' column had 105 missing values (1380 - 1275).
    *   'rain' column had 54 missing values (1380 - 1326).
    *   'Month' column had 10 missing values (1380 - 1370).
    *   'Year' column had 40 missing values (1380 - 1340).
*   Missing values in the 'tem' column were successfully replaced with its mean, which was 25.03.
*   Missing values in the 'rain' column were successfully replaced with its median, which was 140.68.
*   Missing values in the 'Month' column were successfully replaced with its mode, which was 6.
*   Missing values in the 'Year' column were successfully replaced with its mode, which was 1901.
*   A final check confirmed that all 'tem', 'rain', 'Month', and 'Year' columns now have 0 NULL values, indicating complete handling of missing data as per the requirements.

"""